### PR TITLE
Added SIP Calculator feature

### PR DESCRIPTION
**Pull request by Jatinsinha03**
Added SIP Calculator feature which can estimate the returns on your investments.
Updated navbar for every page

Screenshot 2024-10-28 at 1 17 11 AM

### CODE REVIEW

**Comment by vaibhavkothari33** [comment]
hey it's a cool feature but the nav bar for the mobile is too full  try adding the sip button somewhere else might works with nice animation

**Comment by Jatinsinha03** [comment]
Yes that's true. Can it be added to savings.html ?

**Comment by vaibhavkothari33** [comment]
Yes

**Comment by Jatinsinha03** [comment]
Okay then, I will add this to savings.html

**Comment by Jatinsinha03** [comment]
I hope this works !

Screenshot 2024-10-28 at 5 50 03 PM

**Comment by vaibhavkothari33** [comment]
Great

**Pull request merged**
